# Generated by Django 5.2.8 on 2025-11-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(help_text='ID of the task that was prioritized')),
                ('task_title', models.CharField(help_text='Title of the task', max_length=200)),
                ('strategy', models.CharField(help_text='Scoring strategy used', max_length=50)),
                ('priority_score', models.FloatField(help_text='Priority score assigned')),
                ('was_helpful', models.BooleanField(help_text='Whether the user found this prioritization helpful')),
                ('feedback_note', models.TextField(blank=True, help_text='Optional feedback note', null=True)),
                ('task_attributes', models.JSONField(default=dict, help_text='Task attributes at time of feedback (due_date, importance, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Task Feedback',
                'verbose_name_plural': 'Task Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
